version: '3'

networks:
  traefik_proxy:
    external: true

services:
  nginx_2:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    # ports:
    #   - "80:80"
    # expose:
    #   - 80
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_2.rule=Host(`nginx-two.local`)"
      # - "traefik.http.routers.nginx_2.entrypoints=http"
      # - "traefik.http.services.nginx_2.loadbalancer.server.port=80"
