version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:latest
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--entryPoints.http.address=:80"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx_1:
    image: nginx:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_1.rule=Host(`nginx-one.local`)"
      - "traefik.http.routers.nginx_1.entrypoints=http"
      - "traefik.http.services.nginx_1.loadbalancer.server.port=80"

  nginx_2:
    image: nginx:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_2.rule=Host(`nginx-two.local`)"
      - "traefik.http.routers.nginx_2.entrypoints=http"
      - "traefik.http.services.nginx_2.loadbalancer.server.port=80"
